# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Build

on:
  workflow_dispatch:

jobs:
  build_android:
    name: Android build
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v4
        with:
          lfs: true
          submodules: true
      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
      - uses: lukka/get-cmake@latest
      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - name: Set up Android SDK
        uses: android-actions/setup-android@v3
      - name: Build native lib
        run: ./gradlew buildNativeProject
      - name: Build Android bindings
        run: ./gradlew :physx-jni-android:buildNativeProjectAndroid
      - name: Build Android AAR
        run: ./gradlew :physx-jni-android:build

      - name: Upload Android artifacts
        uses: actions/upload-artifact@v4
        with:
          name: android-libs
          path: |
            physx-jni-android/build/outputs/aar/*.aar
            physx-jni-android/build/libs/*.jar
          compression-level: 0
